# Global "top-level" compose file.
# Imports all compose files for individual services.
#
# This structure allows for global variables in the top-level .env to be
# consumed by each service, while still having separation of services into
# distinct compose.yaml files.
---
name: homelab
include:
  - path: services/caddy.yaml
  - path: services/downloadarr.yaml
  - path: services/jellyfin.yaml
  - path: services/metube.yaml
  # - path: services/portainer.yaml
  - path: services/speedtest.yaml
  # - path: services/tailscale.yaml
  # - path: services/unifi.yaml
  - path: services/watchtower.yaml

# networks:
  # TODO
