---
services:
  # authelia:
  #   image: authelia/caddy-duckdns
  #   container_name: caddy
  #   restart: unless-stopped
  #   env_file: ./secrets/authelia.env  

  lldap:
    # image: lldap/lldap:stable-alpine  # Use root on first run to fix permissions
    image: lldap/lldap:stable-alpine-rootless
    container_name: lldap
    restart: unless-stopped
    env_file: ./secrets/lldap.env
    # ports:
      # For LDAP, not recommended to expose, see Usage section.
      #- "3890:3890"
      # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      #- "6360:6360"
      # For the web front-end
      # - "17170:17170"
    volumes:
      # Alternatively, you can mount a local folder
      - "${SERVER_PATH_APPDATA}/lldap:/data"
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - TZ=${SERVER_TIMEZONE}
      # Actual values are stored in secrets/lldap.env
      # - LLDAP_JWT_SECRET=REPLACE_WITH_RANDOM
      # - LLDAP_KEY_SEED=REPLACE_WITH_RANDOM
      # - LLDAP_LDAP_BASE_DN=dc=example,dc=com
      # - LLDAP_LDAP_USER_PASS=adminPas$word
      # If using LDAPS, set enabled true and configure cert and key path
      # - LLDAP_LDAPS_OPTIONS__ENABLED=true
      # - LLDAP_LDAPS_OPTIONS__CERT_FILE=/path/to/certfile.crt
      # - LLDAP_LDAPS_OPTIONS__KEY_FILE=/path/to/keyfile.key
      # If using SMTP, set the following variables
      # - LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET=true
      # - LLDAP_SMTP_OPTIONS__SERVER=smtp.example.com
      # - LLDAP_SMTP_OPTIONS__PORT=465 # Check your smtp providor's documentation for this setting
      # - LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION=TLS # How the connection is encrypted, either "NONE" (no encryption, port 25), "TLS" (sometimes called SSL, port 465) or "STARTTLS" (sometimes called TLS, port 587).
      # - LLDAP_SMTP_OPTIONS__USER=no-reply@example.com # The SMTP user, usually your email address
      # - LLDAP_SMTP_OPTIONS__PASSWORD=PasswordGoesHere # The SMTP password
      # - LLDAP_SMTP_OPTIONS__FROM=no-reply <no-reply@example.com> # The header field, optional: how the sender appears in the email. The first is a free-form name, followed by an email between <>.
      # - LLDAP_SMTP_OPTIONS__TO=admin <admin@example.com> # Same for reply-to, optional.
