---
name: caddy
services:
  caddy:
    # Third party caddy image. Uses `xcaddy` to add module `dns.providers.duckdns`
    # https://github.com/serfriz/caddy-custom-builds/tree/main/caddy-duckdns
    # https://github.com/caddy-dns/duckdns
    # TODO - make my own Dockerfile to remove dependency on a random repo
    image: serfriz/caddy-duckdns
    container_name: caddy
    restart: unless-stopped
    env_file:
      - ./secrets/domain.env
      - ./secrets/caddy.env   # DuckDNS API token, for DNS ACME challenge
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./files/Caddyfile:/etc/caddy/Caddyfile:ro
      - ${SERVER_PATH_CONFIG}/caddy/config:/config
      - ${SERVER_PATH_CONFIG}/caddy/data:/data
      - ${SERVER_PATH_CONFIG}/caddy/static:/www:ro
