---
name: caddy
services:
  caddy:
    # Third party caddy image. Uses `xcaddy` to add module `dns.providers.duckdns`
    # https://github.com/serfriz/caddy-custom-builds/tree/main/caddy-duckdns
    # https://github.com/caddy-dns/duckdns
    # TODO - make my own Dockerfile to remove dependency on a random repo
    image: serfriz/caddy-duckdns
    container_name: caddy
    restart: unless-stopped
    env_file:
      - ./secrets/domain.env
      - ./secrets/caddy.env   # DuckDNS API token, for DNS ACME challenge
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./files/Caddyfile:/etc/caddy/Caddyfile:ro
      - ${SERVER_PATH_APPDATA}/caddy/config:/config
      - ${SERVER_PATH_APPDATA}/caddy/data:/data
      - ${SERVER_PATH_APPDATA}/caddy/static:/www:ro

  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    hostname: wg-easy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - WG_HOST=wg-easy.bulubibu.duckdns.org
    env_file:
      - ./secrets/wg_easy.env
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    volumes:
      - ~/.wg-easy:/etc/wireguard
