---
name: downloadarr
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun  # TODO - make this non generic to support multiple gluetun instances
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=${SERVER_TIMEZONE}
      - UPDATER_PERIOD=24h
    env_file:
      - ./secrets/gluetun.env

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${SERVER_TIMEZONE}
    env_file:
      - ./secrets/domain.env
      - ./secrets/qbittorrent.env  # Pushover API token (unique token for Qbittorrent)
    volumes:
      - ${SERVER_PATH_CONFIG}/qbittorrent:/config
      - ${SERVER_PATH_DATA}/torrents:/data/torrents
      - ${SERVER_PATH_DATA}/media:/data/media
      - ../scripts/qbittorrent:/scripts:ro
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    tty: true  # TODO - is this really needed?

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${SERVER_TIMEZONE}
    volumes:
      - ${SERVER_PATH_CONFIG}/bazarr:/config
      - ${SERVER_PATH_DATA}:/data  # Entire data folder

  flaresolverr:
    image: flaresolverr/flaresolverr
    container_name: flaresolverr
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${SERVER_TIMEZONE}

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${SERVER_TIMEZONE}
    volumes:
      - ${SERVER_PATH_CONFIG}/prowlarr:/config

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${SERVER_TIMEZONE}
    volumes:
      - ${SERVER_PATH_CONFIG}/radarr:/config
      - ${SERVER_PATH_DATA}:/data  # Entire data folder, to allow hardlinks

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${SERVER_TIMEZONE}
    volumes:
      - ${SERVER_PATH_CONFIG}/sonarr:/config
      - ${SERVER_PATH_DATA}:/data  # Entire data folder, to allow hardlinks
