---
name: jellyfin
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    group_add:
      - ${GID_RENDER}  # render (on host)
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128  # Use GPU for encoding
    environment:
      - TZ=${SERVER_TIMEZONE}
    ports:
      - 8096:8096
    volumes:
      - ${SERVER_PATH_APPDATA}/jellyfin:/config
      - ${SERVER_PATH_CACHE}/jellyfin:/cache
      # Cannot change the media path without losing library metadata, so it's slightly different to
      # the new structure on disk as seen by other containers - shouldn't be an issue.
      - type: bind
        source: ${SERVER_PATH_MEDIA}/library
        target: /data/media

  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - TZ=${SERVER_TIMEZONE}
    ports:
      - 5055:5055
    volumes:
      - ${SERVER_PATH_APPDATA}/jellyseerr:/app/config
