---
name: jellyfin
services:
  jellyfin:
    image: jellyfin/jellyfin
    group_add:
      - ${GID_RENDER}  # render (on host)
    container_name: jellyfin
    restart: unless-stopped
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128  # Use GPU for encoding
    environment:
      - JELLYFIN_PublishedServerUrl=${EXTERNAL_URL_JELLYFIN}
      - TZ=${SERVER_TIMEZONE}
    ports:
      - "${JELLYFIN_WEBUI_PORT}:8096"
    volumes:
      - ${SERVER_PATH_CONFIG}/jellyfin/config:/config
      - ${SERVER_PATH_CACHE}/jellyfin:/cache
      - type: bind
        source: ${SERVER_PATH_DATA}/media
        target: /data/media

  jellyseerr:
    image: fallenbagel/jellyseerr
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - TZ=${SERVER_TIMEZONE}
    ports:
      - "${JELLYSEERR_WEBUI_PORT}:5055"
    volumes:
      - ${SERVER_PATH_CONFIG}/jellyseerr:/app/config
