---
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    volumes:
      - ${SERVER_PATH_MEDIA}/library/other:/downloads
  yt-dlp:
    image: nbr23/youtube-dl-server:yt-dlp
    container_name: yt-dlp
    restart: unless-stopped
    volumes:
      - ${SERVER_PATH_MEDIA}/library/other:/youtube-dl
      - ./files/yt-dlp_config.yaml:/app_config/config.yml:ro
