---
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    volumes:
      # Temp workaround - doesn't seem to play nice with network shares
      - /home/jaden/appdata/open-webui:/app/backend/data
      # - ${SERVER_PATH_APPDATA}/open-webui:/app/backend/data
