---
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    volumes:
      - ${SERVER_PATH_APPDATA}/open-webui:/app/backend/data
