---
name: speedtest
services:
  speedtest-tracker:
    image: linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${SERVER_TIMEZONE}
      - DB_CONNECTION=sqlite
      - DISPLAY_TIMEZONE=${SERVER_TIMEZONE}
      - PRUNE_RESULTS_OLDER_THAN=365
      - PUBLIC_DASHBOARD=true
      - SPEEDTEST_SCHEDULE="0 * * * *"
    env_file:
      - ./secrets/speedtest.env  # Contains APP_KEY which is a required env var
    volumes:
      - ${SERVER_PATH_APPDATA}/speedtest-tracker:/config

  librespeed:
    container_name: librespeed
    image: linuxserver/librespeed:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${SERVER_TIMEZONE}
      - MODE=standalone
      - DB_TYPE=sqlite
    volumes:
      - ${SERVER_PATH_APPDATA}/librespeed:/database
